### PR TITLE
Updates package keywords

### PR DESCRIPTION
**Pull request by Jwaegebaert**
Related to: https://github.com/pnp/cli-microsoft365/issues/5433

### CODE REVIEW

**Comment by garrytrinder** [comment]
Thanks for the PR @Jwaegebaert 

Looks like the build error is related to the change to ESM in v7.

**Comment by garrytrinder** [comment]
I was wrong, it was caused by incorrect `tsconfig.json` configuration.

**Comment by garrytrinder** [comment]
I've merged #32, @Jwaegebaert if you can rebase your PR the tests should then pass.

**Comment by Jwaegebaert** [comment]
Awesome, green checks all the way.

**Comment by garrytrinder** [comment]
Merged 🚀

Thanks @Jwaegebaert 👍

**Pull request merged**
