### PR TITLE
Fixes app id not found.

### LINKED ISSUE #18: `spo app add` not returning `UniqueId` anymore.
Originates from: https://github.com/pnp/action-cli-deploy/issues/11#issuecomment-1322358369

Apparently we broke the GitHub action flow by defining the default `output` in the CLI runtime. Because of this issue: https://github.com/pnp/cli-microsoft365/issues/3445

Our default `output` value used to be `undefined`, by refactoring this to `json`, the command will now return the entire app object instead of just the ID.

https://github.com/pnp/cli-microsoft365/blob/e42aed1530b6755b2485a944bbd9a251aac3fddb/src/m365/spo/commands/app/app-add.ts#L127-L132

Therefore these lines of code will fail:

https://github.com/pnp/action-cli-deploy/blob/6014072c7a52ec213896ba46e792ddef1b3e971e/src/main.ts#L27-L28

https://github.com/pnp/action-cli-deploy/blob/6014072c7a52ec213896ba46e792ddef1b3e971e/src/main.ts#L31-L32

### PR DESCRIPTION
**Pull request by milanholemans**
Closes #18

### CODE REVIEW

**Comment by garrytrinder** [comment]
Before we merge this, we should consider completing https://github.com/pnp/action-cli-deploy/issues/17 to bring the repo in line with the `action-cli-login` action.

**Comment by milanholemans** [comment]
> Before we merge this, we should consider completing #17 to bring the repo in line with the `action-cli-login` action.

Ok, but these seems to be like a "nice to have" isn't it? While this is a bug fix because the GitHub action is currently not working.

**Comment by martinlingstuyl** [comment]
Yeah, I agree with @milanholemans here, let’s get this fixed asap.

**Comment by martinlingstuyl** [comment]
@milanholemans, I’m not sure, but I think we should bump the version number in the package.json as well…

**Comment by milanholemans** [comment]
> @milanholemans, I’m not sure, but I think we should bump the version number in the package.json as well…

Seems like a valid point indeed, thx for the feedback.

**Comment by martinlingstuyl** [comment]
…and update the release notes section of readme.md @milanholemans

**Comment by milanholemans** [comment]
> …and update the release notes section of readme.md @milanholemans

Should this be done? Seems like not all versions are getting mentioned in the release notes (current is 2.0.1).

**Comment by martinlingstuyl** [comment]
> > …and update the release notes section of readme.md @milanholemans
> 
> Should this be done? Seems like not all versions are getting mentioned in the release notes (current is 2.0.1).

I’d say thats important, yes. Apparently it’s been forgotten in the past.

**Comment by martinlingstuyl** [comment]
Looks great, merged! Thanks for picking it up, will you check with the reporting user so that he can verify?

**Comment by milanholemans** [comment]
> Looks great, merged! Thanks for picking it up, will you check with the reporting user so that he can verify?

Certainly, thank you @martinlingstuyl!

**Pull request merged**
